DynamicRoleWeb/ViewModels/UserMenuViewModel.cs
namespace DynamicRoleWeb.ViewModels
{
    public class UserMenuViewModel
    {
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string AreaName { get; set; }
        public string ControllerName { get; set; }
        public int Actionid {  get; set; }
        public string ActionName {  get; set; }
        public bool Permitted { get; set; }
        public bool IsChecked { get; set; }
    }
}

DynamicRoleWeb/Areas/Administrator/Controllers/CommonAjaxController.cs
using DynamicRoleWeb.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DynamicRoleWeb.Areas.Administrator.Controllers
{
    [Area("Administrator")]
    [Authorize]
    public class CommonAjaxController : Controller
    {
        private readonly IDataAccessService _dataAccessService;
        public CommonAjaxController(IDataAccessService dataAccessService)
        {
            _dataAccessService = dataAccessService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public JsonResult LoadActionName(int areaControllerId)
        {
            var ActionList = _dataAccessService.LoadActionNames(areaControllerId);
            var actionNameSelectList = new SelectList(ActionList.ToList(), "Id", "ActionName");
            return Json(new {returnActionNameList = actionNameSelectList, IsSuccess = true});
        }
    }
}

DynamicRoleWeb/Areas/Administrator/Controllers/UserMenuController.cs
using DynamicRoleWeb.Models;
using DynamicRoleWeb.Services;
using DynamicRoleWeb.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SQLitePCL;
using System;

namespace DynamicRoleWeb.Areas.Administrator.Controllers
{
    [Area("Administrator")]
    [Authorize]
    public class UserMenuController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IDataAccessService _dataAccessService;

        public UserMenuController(UserManager<IdentityUser> userManager, IDataAccessService dataAccessService)
        {
            _userManager = userManager;
            _dataAccessService = dataAccessService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetAreas()
        {
            var areas = _dataAccessService.LoadAreasFromDbAndRefelction();
            return View(areas);
        }

        [HttpGet]
        public IActionResult CreateArea()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateArea(MenuGroupViewModel model)
        {
            if (ModelState.IsValid)
            {
                _dataAccessService.AddMenuGroup(model);
                return RedirectToAction("GetAreas");
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult GetController()
        {
            var controller = _dataAccessService.GetControllerThrowDbAndReflection();

            return View(controller);
        }

        [HttpPost]
        public IActionResult AddController(List<AreaControllerViewModel> list)
        {
            if (list == null)
            {
                return RedirectToAction("GetController");
            }

            _dataAccessService.AddAreaControllerToDb(list);

            return RedirectToAction("GetController");
        }

        [HttpGet]
        public IActionResult GetActions()
        {
            var Actions = _dataAccessService.GetActionsThrowReflectionAndDb();
            return View(Actions);
        }

        [HttpPost]
        public IActionResult AddActions(List<ActionsViewModel> list)
        {
            if (list == null)
            {
                return RedirectToAction("GetActions");
            }

            _dataAccessService.AddActionsToDb(list);
            return RedirectToAction("GetActions");
        }

        [HttpGet]
        public IActionResult Getmenu()
        {
            var Actiondata = _dataAccessService.GetActionsFromDb();
            var parent = _dataAccessService.GetMenusFromDb();
            ViewData["Actions"] = new SelectList(Actiondata, "Id", "ActionName");
            ViewData["Parent"] = new SelectList(parent, "Id", "DisplayName");
            return View();
        }

        [HttpPost]
        public IActionResult AddMenu(MenuViewModel model)
        {
            if (model == null)
            {
                return RedirectToAction("Getmenu");
            }

            _dataAccessService.AddMenuToDb(model);
            return RedirectToAction("Getmenu");
        }

        [HttpGet]
        public IActionResult ShowMenus()
        {
            var data = _dataAccessService.LoadMenus();
            return View(data);
        }
        [HttpGet]
        public async Task<IActionResult> Users()
        {
            var userViewModel = new List<UserMenuViewModel>();

            var users = await _userManager.Users.ToListAsync();
            foreach (var item in users)
            {
                if (item.UserName != "superadmin@gmail.com")
                {
                    userViewModel.Add(new UserMenuViewModel()
                    {
                        UserId = item.Id,
                        Email = item.Email,
                        UserName = item.UserName,
                    });
                }

            }

            return View(userViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> EditUserMenuPermission(string id)
        {
            List<UserMenuViewModel> list = new List<UserMenuViewModel>();
            if (!string.IsNullOrWhiteSpace(id))
            {
                var user = await _userManager.FindByIdAsync(id);
                ViewBag.UserName = user?.UserName;

                //var allActions = _dataAccessService.GetActionsFromDb();
                var menus = _dataAccessService.GetAllMenus();
                # region Previous
                //foreach (var action in allActions)
                //{
                //    var getAreaController = _dataAccessService.GetAreaControllerName(action.AreaControllerId);
                //    var getArea = _dataAccessService.GetAreaUsingAreaControllerId(getAreaController.MenuGroupId);
                //    var isPresent = _dataAccessService.isAlreadyPermitted(action.Id, id);
                //    var item = new UserMenuViewModel
                //    {
                //        UserId = id,
                //        AreaName = getArea.AreaName,
                //        ControllerName = getAreaController.ControllerName,
                //        ActionName = action.ActionName,
                //        Actionid = action.Id,
                //        Permitted = isPresent
                //    };
                //    list.Add(item);
                //}
                #endregion

                foreach (var menu in menus)
                {
                    var isPresent = _dataAccessService.isAlreadyPermitted(menu.Id, id);
                    var item = new UserMenuViewModel
                    {
                        UserId = id,
                        AreaName = menu.AreaName,
                        ControllerName = menu.ControllerName,
                        ActionName = menu.ActionName,
                        Actionid = menu.ActionId,
                        Permitted = isPresent,
                        IsChecked = isPresent,
                    };
                    list.Add(item);
                }
            }

            return View(list);
        }

        [HttpPost]
        public IActionResult EditUserMenuPermission(List<UserMenuViewModel> list)
        {
            if(list == null || list.Count == 0)
            {
                return RedirectToAction("Users");
            }

            _dataAccessService.AddUserMenuPermission(list);

            return RedirectToAction("Users");
        }

        public IActionResult CheckControllerAccess()
        {
           // var actionList = new List<NameValueViewModel>();
            var areaController = _dataAccessService.LoadAreaController();
            ViewBag.AreaControllerList = new SelectList(areaController, "Id", "ControllerName");
            List<SelectListItem> emptyList = new List<SelectListItem>();
            ViewBag.ActionList = new SelectList(emptyList, "Value", "Text");
            return View();
        }
    }
}

DynamicRoleWeb/Areas/Administrator/Views/UserMenu/CheckControllerAccess.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row pb-3">
    <div class="col-6">
        <h4>Check Menu Access</h4>
    </div>
</div>

<div class="container">
    <div class="row mb-3">
        <label class="col-md-2 col-form-label">Controller Name</label>
        <div class="col-md-6">
            @Html.DropDownList("AreaController", ViewBag.AreaControllerList as SelectList, "--select--", new { @class = "form-select" })
        </div>
    </div>
    <div class="row mb-3">
        <label class="col-md-2 col-form-label">Action Name</label>
        <div class="col-md-6">
            @Html.DropDownList("ActionName", ViewBag.ActionList as SelectList, new { @class = "form-select" })
        </div>
    </div>
</div>

@section scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script>
        $(document).ready(function () {
            $(document).on('change', '#AreaController', function (e) {
                var AreaControllerId = $(this).val();
                if (AreaControllerId) {
                    let url = '@Url.Action("LoadActionName", "CommonAjax")';
                    let data = { areaControllerId: AreaControllerId };
                    $.ajax({
                        type: "POST",
                        url: url,
                        cache: false,
                        async: true,
                        data: data,
                        success: function (response) {
                            console.log(response)
                            if (response.isSuccess) {
                                var actionSelect = $('#ActionName');
                                actionSelect.html('');
                                $.each(response.returnActionNameList, function (i, v) {
                                    actionSelect.append($('<option>', {
                                        value: v.value,
                                        text: v.text
                                    }));
                                });
                            }
                        },
                        error: function (xhr, status, error) {
                            console.error(xhr.responseText);
                        }
                    });
                }
            });
        });
    </script>
}

DynamicRoleWeb/Areas/Administrator/Views/UserMenu/CreateArea.cshtml
@model DynamicRoleWeb.ViewModels.MenuGroupViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("CreateArea", "UserMenu", FormMethod.Post))
{
    <div class="form-group pb-2">
        @Html.LabelFor(model => model.AreaName)
        @Html.TextBoxFor(model => model.AreaName, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.AreaName, "", new { @class = "text-danger" })
    </div>

    <button type="submit" class="btn btn-primary">Save</button>
}

DynamicRoleWeb/Areas/Administrator/Views/UserMenu/EditUserMenuPermission.cshtml
@model List<DynamicRoleWeb.ViewModels.UserMenuViewModel>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row pb-3">
    <div class="col-6">
        <h4>Menu Permission for <span class="text-danger">@ViewBag.UserName</span> </h4>
    </div>
</div>
@if(Model.Count > 0)
{
    <div class="pb-2">
        <h4 class="text-decoration-underline">Area - Controller - Action </h4>
    </div>
    @using (Html.BeginForm("EditUserMenuPermission", "UserMenu", FormMethod.Post))
    {
        <div class="form-group pb-2">
            <ul style="list-style-type: none; padding-left:0px;">
                @for (var i = 0; i < Model.Count; i++)
                {
                    <li>
                        <input type="checkbox" class="controller-checkbox" data-index="@i" checked="@Model[i].Permitted" />
                        <label style="margin-left:10px" asp-for="@Model[i].ActionName">@Model[i].AreaName - @Model[i].ControllerName - @Model[i].ActionName </label>
                        <input type="hidden" name="list[@i].Actionid" value="@Model[i].Actionid" />
                        <input type="hidden" name="list[@i].UserId" value="@Model[i].UserId" />
                        <input type="hidden" name="list[@i].IsChecked" id="permitted-@i" value="@Model[i].IsChecked" />
                    </li>
                }
            </ul>
        </div>
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    }

}
else
{
    <div class="pb-2">
        <h4 class="text-danger">No Menu Found...</h4>
    </div>
}

@section scripts {
    <script>
        $(document).ready(function () {
            $('.controller-checkbox').each(function () {
                var index = $(this).data('index');
                var isChecked = $(this).is(':checked');
                $('#permitted-' + index).val(isChecked);
            });

            $('.controller-checkbox').change(function () {
                var index = $(this).data('index');
                var isChecked = $(this).is(':checked');
                $('#permitted-' + index).val(isChecked);
            });
        });
    </script>
}

DynamicRoleWeb/Areas/Administrator/Views/UserMenu/GetActions.cshtml
@model List<DynamicRoleWeb.ViewModels.ActionsViewModel>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row pb-3">
    <div class="col-6">
        <h4>Action Methods</h4>
    </div>
</div>
@if(Model.Count > 0)
{
    <div>
        <h4 class="text-decoration-underline">Controller Name - Action Method </h4>
    </div>
    @using (Html.BeginForm("AddActions", "UserMenu", FormMethod.Post))
    {
        <div class="form-group pb-2">
            <ul style="list-style-type: none; padding-left:0px;">
                @for (var i = 0; i < Model.Count; i++)
                {
                    <li>
                        <input type="checkbox" class="controller-checkbox" data-index="@i" checked="@Model[i].IsPresent" />
                        <label style="margin-left:10px" asp-for="@Model[i].ActionName">@Model[i].AreaControllerName - @Model[i].ActionName </label>
                        <input type="hidden" name="list[@i].AreaControllerId" value="@Model[i].AreaControllerId" />
                        <input type="hidden" name="list[@i].ActionName" value="@Model[i].ActionName" />
                        <input type="hidden" name="list[@i].IsChecked" id="permitted-@i" value="@Model[i].IsChecked" />
                    </li>
                }
            </ul>
        </div>
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    }

}
else
{
    <h2 class="text-danger">No Action is available now...</h2>
}

@section scripts {
    <script>
        $(document).ready(function () {
            $('.controller-checkbox').change(function () {
                var index = $(this).data('index');
                var isChecked = $(this).is(':checked');
                $('#permitted-' + index).val(isChecked);
            });
        });
    </script>
}

DynamicRoleWeb/Areas/Administrator/Views/UserMenu/GetAreas.cshtml
@model List<DynamicRoleWeb.ViewModels.MenuGroupViewModel>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row pb-3">
    <div class="col-6">
        <h4>Areas</h4>
    </div>
    <div class="col-6 text-end">
        @Html.ActionLink("Create Area", "CreateArea", "UserMenu",null, new {@class = "btn btn-primary" })
    </div>
</div>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>sl</th>
            <th>Area Name</th>
        </tr>
    </thead>
    <tbody>
        @{
            int i = 1;
        }
        @foreach(var item in Model)
        {
            <tr>
                <td>@i</td>
                <td>@item.AreaName</td>
            </tr>
            i++;
        }
    </tbody>
</table>

DynamicRoleWeb/Areas/Administrator/Views/UserMenu/GetController.cshtml
@model List<DynamicRoleWeb.ViewModels.AreaControllerViewModel>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row pb-3">
    <div class="col-6">
        <h4>Controllers (Area - Controller)</h4>
    </div>
</div>
@using (Html.BeginForm("AddController", "UserMenu", FormMethod.Post))
{
    <div class="form-group pb-2">
        <ul style="list-style-type: none; padding-left:0px;">
            @for(var i = 0; i < Model.Count; i++)
            {
                <li>
                    <input type="checkbox" class="controller-checkbox" data-index="@i" checked="@Model[i].Permitted"/>
                    <label style="margin-left:10px" asp-for="@Model[i].ControllerName">@Model[i].AreaName - @Model[i].ControllerName</label>
                    <input type="hidden" name="list[@i].ControllerName" value="@Model[i].ControllerName" />
                    <input type="hidden" name="list[@i].AreaName" value="@Model[i].AreaName" />
                    <input type="hidden" name="list[@i].IsChecked" id="permitted-@i" value="@Model[i].IsChecked" />
                </li>
            }
        </ul>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>  
}
@section scripts {
    <script>
        $(document).ready(function() {
            $('.controller-checkbox').change(function() {
                var index = $(this).data('index');
                var isChecked = $(this).is(':checked');
                $('#permitted-' + index).val(isChecked);
            });
        });
    </script>
}

DynamicRoleWeb/Areas/Administrator/Views/UserMenu/GetMenu.cshtml
@model DynamicRoleWeb.ViewModels.MenuViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row pb-3">
    <div class="col-6">
        <h4>Menu</h4>
    </div>
    <div class="col-6 text-end">
        @Html.ActionLink("Show menus", "ShowMenus", "UserMenu", null, new { @class = "btn btn-success" })
    </div>
</div>

@using (Html.BeginForm("AddMenu", "UserMenu", new { area = "Administrator" }, FormMethod.Post))
{


    <div class="form-group">
        @Html.LabelFor(model => model.ActionName, new { @class = "col-form-label" })
        @Html.DropDownListFor(model => model.ActionId, ViewData["Actions"] as SelectList, "--Select--", new { @class = "form-select col-md-6" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.DisplayName, new { @class = "col-form-label" })
        @Html.EditorFor(model => model.DisplayName, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ParentName, new { @class = "col-form-label" })
        @Html.DropDownListFor(model => model.ParentsId, ViewData["Parent"] as SelectList, "--Select--", new { @class = "form-select col-md-6" })
    </div>

    <div class="form-group pt-2">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
}

DynamicRoleWeb/Areas/Administrator/Views/UserMenu/ShowMenus.cshtml
@model List<DynamicRoleWeb.ViewModels.MenuViewModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row pb-3">
    <div class="col-6">
        <h4>Menu With It's Parent Menu</h4>
    </div>
    <div class="col-6 text-end">
        @Html.ActionLink("Go Back", "Getmenu", "UserMenu", null, new { @class = "btn btn-success" })
    </div>
</div>
<table class="table table-striped table-hover text-center">
    <thead>
        <tr>
            <th>sl</th>
            <th>Action Name</th>
            <th>Parent Name</th>
            <th>Display Name</th>
        </tr>
    </thead>
    <tbody>
        @{
            int i = 1;
        }
        @foreach(var item in Model)
        {
            <tr>
                <td>@i</td>
                <td>@item.ActionName</td>
                <td>@(item.ParentName != "" ? item.ParentName : "_")</td>
                <td>@item.DisplayName</td>
            </tr>
        }
    </tbody>
</table>

DynamicRoleWeb/Areas/Administrator/Views/UserMenu/Users.cshtml
@model List<DynamicRoleWeb.ViewModels.UserMenuViewModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row pb-3">
    <div class="col-6">
        <h4>Users</h4>
    </div>
   
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                User Name
            </th>
            <th>
                Email
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.ActionLink("Edit User Permission", "EditUserMenuPermission", "UserMenu",  new { id = item.UserId},new{ @class = "btn btn-outline-success" })
                </td>
            </tr>
        }
    </tbody>
</table>